RepoName: mengjunwei-mjw/quickstart-nextcloud-all-in-one
RunCommand: |
  echo "start run command"
SourceCodePath: .
CommandTimeout: 3600
SecurityGroupPorts:
- 80
RuntimeType: LinuxShell
ServicePorts:
- 80
ServiceType: private
ArtifactSourceType: SourceCode
ImageId: '"{{resolve:oos:aliyun/services/computenest/images/aliyun_3_2104_java_17}}"'
ServiceBuildRegion: ap-southeast-1
RegionId: cn-hangzhou
CustomParameters: ''
Owner: mengjunwei-mjw
Branch: gh-pages
Platform: github
